// GENERATED FILE — from chains.yaml via tool/gen_chains.dart. DO NOT EDIT.

/// One chain's metadata, generated from [chains.yaml] at repo root.
/// Regenerate with: dart run tool/gen_chains.dart
class ChainEntry {
  final String key;
  final String ticker;
  final String name;
  final String family;
  final String rpc;
  final String gasToken;
  /// 'swap' (wired into xfg-swapd orderbook) or 'wallet' (ERC20 layer only).
  final String tier;
  final String icon;
  final int chainId;
  final int confirmBlocks;
  /// Brand color as 0xRRGGBB (no alpha byte).
  final int colorValue;

  const ChainEntry({
    required this.key,
    required this.ticker,
    required this.name,
    required this.family,
    required this.rpc,
    required this.gasToken,
    required this.tier,
    required this.icon,
    required this.chainId,
    required this.confirmBlocks,
    required this.colorValue,
  });

  bool get isWalletTier => tier == 'wallet';
}

const List<ChainEntry> kChains = [
  ChainEntry(key: 'eth', ticker: 'ETH', name: 'Ethereum', family: 'evm', rpc: 'https://eth.llamarpc.com', gasToken: 'ETH', tier: 'swap', icon: 'assets/coin icons/eth.png', chainId: 1, confirmBlocks: 12, colorValue: 0x627EEA),
  ChainEntry(key: 'arb', ticker: 'ARB', name: 'Arbitrum', family: 'evm', rpc: 'https://arb1.arbitrum.io/rpc', gasToken: 'ETH', tier: 'swap', icon: 'assets/coin icons/arb.png', chainId: 42161, confirmBlocks: 20, colorValue: 0x28A0F0),
  ChainEntry(key: 'base', ticker: 'BASE', name: 'Base', family: 'evm', rpc: 'https://mainnet.base.org', gasToken: 'ETH', tier: 'swap', icon: 'assets/coin icons/base.png', chainId: 8453, confirmBlocks: 1, colorValue: 0x0052FF),
  ChainEntry(key: 'bsc', ticker: 'BNB', name: 'BNB Chain', family: 'evm', rpc: 'https://bsc-dataseed.binance.org', gasToken: 'BNB', tier: 'swap', icon: 'assets/coin icons/bnb.png', chainId: 56, confirmBlocks: 3, colorValue: 0xF0B90B),
  ChainEntry(key: 'poly', ticker: 'POLY', name: 'Polygon', family: 'evm', rpc: 'https://polygon-rpc.com', gasToken: 'POL', tier: 'swap', icon: 'assets/coin icons/matic.png', chainId: 137, confirmBlocks: 1, colorValue: 0x8247E5),
  ChainEntry(key: 'op', ticker: 'OP', name: 'OP Mainnet', family: 'evm', rpc: 'https://mainnet.optimism.io', gasToken: 'ETH', tier: 'wallet', icon: 'assets/coin icons/op.jpg', chainId: 10, confirmBlocks: 1, colorValue: 0xFF0420),
  ChainEntry(key: 'avax', ticker: 'AVAX', name: 'Avalanche', family: 'evm', rpc: 'https://api.avax.network/ext/bc/C/rpc', gasToken: 'AVAX', tier: 'wallet', icon: 'assets/coin icons/avax.png', chainId: 43114, confirmBlocks: 1, colorValue: 0xE84142),
  ChainEntry(key: 'cro', ticker: 'CRO', name: 'Cronos', family: 'evm', rpc: 'https://evm.cronos.org', gasToken: 'CRO', tier: 'wallet', icon: 'assets/coin icons/cronos.png', chainId: 25, confirmBlocks: 1, colorValue: 0x002D74),
  ChainEntry(key: 'monad', ticker: 'MON', name: 'Monad', family: 'evm', rpc: 'https://rpc.monad.xyz', gasToken: 'MON', tier: 'wallet', icon: 'assets/coin icons/monad.png', chainId: 143, confirmBlocks: 1, colorValue: 0x836EF9),
  ChainEntry(key: 'xpl', ticker: 'XPL', name: 'Plasma', family: 'evm', rpc: 'https://rpc.plasma.to', gasToken: 'XPL', tier: 'wallet', icon: 'assets/coin icons/xpl.png', chainId: 9745, confirmBlocks: 1, colorValue: 0x4FA9E0),
  ChainEntry(key: 'pls', ticker: 'PLS', name: 'PulseChain', family: 'evm', rpc: 'https://rpc.pulsechain.com', gasToken: 'PLS', tier: 'wallet', icon: 'assets/coin icons/pls.png', chainId: 369, confirmBlocks: 1, colorValue: 0x9C27B0),
  ChainEntry(key: 'uni', ticker: 'UNI', name: 'Unichain', family: 'evm', rpc: 'https://mainnet.unichain.org', gasToken: 'ETH', tier: 'wallet', icon: 'assets/coin icons/uni.png', chainId: 130, confirmBlocks: 1, colorValue: 0xFF007A),
  ChainEntry(key: 'rh', ticker: 'RHC', name: 'Robinhood Chain', family: 'evm', rpc: 'https://rpc.mainnet.chain.robinhood.com', gasToken: 'ETH', tier: 'wallet', icon: 'assets/coin icons/rhc.png', chainId: 4663, confirmBlocks: 1, colorValue: 0x6B7280),
  ChainEntry(key: 'bob', ticker: 'BOB', name: 'BOB', family: 'evm', rpc: 'https://rpc.nodeflare.app/bob/public', gasToken: 'ETH', tier: 'wallet', icon: 'assets/coin icons/bob.png', chainId: 60808, confirmBlocks: 1, colorValue: 0xFF6D00),
  ChainEntry(key: 'gleec', ticker: 'GLEEC', name: 'Gleec Chain', family: 'evm', rpc: 'https://evm-rpc.gleec.com', gasToken: 'GLEEC', tier: 'wallet', icon: 'assets/coin icons/gleec.png', chainId: 11169, confirmBlocks: 1, colorValue: 0x00A3C4),
  ChainEntry(key: 'linea', ticker: 'LINEA', name: 'Linea', family: 'evm', rpc: 'https://rpc.linea.build', gasToken: 'ETH', tier: 'wallet', icon: 'assets/coin icons/linea.png', chainId: 59144, confirmBlocks: 1, colorValue: 0x61DFFF),
  ChainEntry(key: 'zksync', ticker: 'ZKS', name: 'ZKsync Era', family: 'evm', rpc: 'https://mainnet.era.zksync.io', gasToken: 'ETH', tier: 'wallet', icon: 'assets/coin icons/zksync.png', chainId: 324, confirmBlocks: 1, colorValue: 0x8C8DFC),
  ChainEntry(key: 'hyperevm', ticker: 'HYPER', name: 'HyperEVM', family: 'evm', rpc: 'https://rpc.hyperliquid.xyz/evm', gasToken: 'HYPE', tier: 'wallet', icon: 'assets/coin icons/hyperevm.png', chainId: 999, confirmBlocks: 1, colorValue: 0x97FCE4),
  ChainEntry(key: 'ink', ticker: 'INK', name: 'Ink', family: 'evm', rpc: 'https://rpc-gel.inkonchain.com', gasToken: 'ETH', tier: 'wallet', icon: 'assets/coin icons/ink.png', chainId: 57073, confirmBlocks: 1, colorValue: 0x7132F5),
  ChainEntry(key: 'rsk', ticker: 'RSK', name: 'Rootstock', family: 'evm', rpc: 'https://public-node.rsk.co', gasToken: 'RBTC', tier: 'wallet', icon: 'assets/coin icons/rsk.png', chainId: 30, confirmBlocks: 15, colorValue: 0xE9B64E),
  ChainEntry(key: 'gnosis', ticker: 'GNO', name: 'Gnosis', family: 'evm', rpc: 'https://rpc.gnosischain.com', gasToken: 'XDAI', tier: 'wallet', icon: 'assets/coin icons/gnosis.png', chainId: 100, confirmBlocks: 1, colorValue: 0x1D6C4E),
  ChainEntry(key: 'flare', ticker: 'FLR', name: 'Flare', family: 'evm', rpc: 'https://flare-api.flare.network/ext/C-rpc', gasToken: 'FLR', tier: 'wallet', icon: 'assets/coin icons/flare.png', chainId: 14, confirmBlocks: 1, colorValue: 0xE6413E),
  ChainEntry(key: 'kaia', ticker: 'KAIA', name: 'Kaia', family: 'evm', rpc: 'https://public-en.node.kaia.io', gasToken: 'KAIA', tier: 'wallet', icon: 'assets/coin icons/kaia.png', chainId: 8217, confirmBlocks: 1, colorValue: 0xFF1D01),
  ChainEntry(key: 'scroll', ticker: 'SCR', name: 'Scroll', family: 'evm', rpc: 'https://rpc.scroll.io', gasToken: 'ETH', tier: 'wallet', icon: 'assets/coin icons/scroll.png', chainId: 534352, confirmBlocks: 1, colorValue: 0xEBC28E),
  ChainEntry(key: 'abstract', ticker: 'ABS', name: 'Abstract', family: 'evm', rpc: 'https://rpc.abstract.xyz', gasToken: 'ETH', tier: 'wallet', icon: 'assets/coin icons/abstract.png', chainId: 2741, confirmBlocks: 1, colorValue: 0x202020),
  ChainEntry(key: 'plume', ticker: 'PLUME', name: 'Plume', family: 'evm', rpc: 'https://rpc.plume.org', gasToken: 'PLUME', tier: 'wallet', icon: 'assets/coin icons/plume.png', chainId: 98866, confirmBlocks: 1, colorValue: 0xFF3D00),
  ChainEntry(key: 'soneium', ticker: 'SONEIUM', name: 'Soneium', family: 'evm', rpc: 'https://rpc.soneium.org', gasToken: 'ETH', tier: 'wallet', icon: 'assets/coin icons/soneium.png', chainId: 1868, confirmBlocks: 1, colorValue: 0x937DFF),
  ChainEntry(key: 'doma', ticker: 'DOMA', name: 'Doma', family: 'evm', rpc: 'https://rpc.doma.xyz', gasToken: 'ETH', tier: 'wallet', icon: 'assets/coin icons/doma.png', chainId: 97477, confirmBlocks: 1, colorValue: 0x4F46E5),
  ChainEntry(key: 'beam', ticker: 'BEAM', name: 'Beam', family: 'evm', rpc: 'https://build.onbeam.com/rpc', gasToken: 'BEAM', tier: 'wallet', icon: 'assets/coin icons/beam.png', chainId: 4337, confirmBlocks: 1, colorValue: 0x0BDBB5),
  ChainEntry(key: 'moonriver', ticker: 'MOVR', name: 'Moonriver', family: 'evm', rpc: 'https://rpc.api.moonriver.moonbeam.network', gasToken: 'MOVR', tier: 'wallet', icon: 'assets/coin icons/moonriver.png', chainId: 1285, confirmBlocks: 1, colorValue: 0xF5B700),
  ChainEntry(key: 'peaq', ticker: 'PEAQ', name: 'peaq', family: 'evm', rpc: 'https://peaq.api.onfinality.io/public', gasToken: 'PEAQ', tier: 'wallet', icon: 'assets/coin icons/peaq.png', chainId: 3338, confirmBlocks: 1, colorValue: 0x7A2BF5),
  ChainEntry(key: 'tempo', ticker: 'TEMPO', name: 'Tempo', family: 'evm', rpc: 'https://rpc.tempo.xyz', gasToken: '', tier: 'wallet', icon: 'assets/coin icons/tempo.png', chainId: 4217, confirmBlocks: 1, colorValue: 0x111111),
  ChainEntry(key: 'sei', ticker: 'SEI', name: 'Sei', family: 'evm', rpc: 'https://evm-rpc.sei-apis.com', gasToken: 'SEI', tier: 'wallet', icon: 'assets/coin icons/sei.png', chainId: 1329, confirmBlocks: 1, colorValue: 0x9E1F19),
];

final Map<String, ChainEntry> kChainByKey = {for (final c in kChains) c.key: c};

const Map<String, int> kChainIds = {
  'eth': 1,
  'arb': 42161,
  'base': 8453,
  'bsc': 56,
  'poly': 137,
  'op': 10,
  'avax': 43114,
  'cro': 25,
  'monad': 143,
  'xpl': 9745,
  'pls': 369,
  'uni': 130,
  'rh': 4663,
  'bob': 60808,
  'gleec': 11169,
  'linea': 59144,
  'zksync': 324,
  'hyperevm': 999,
  'ink': 57073,
  'rsk': 30,
  'gnosis': 100,
  'flare': 14,
  'kaia': 8217,
  'scroll': 534352,
  'abstract': 2741,
  'plume': 98866,
  'soneium': 1868,
  'doma': 97477,
  'beam': 4337,
  'moonriver': 1285,
  'peaq': 3338,
  'tempo': 4217,
  'sei': 1329,
};

const Map<String, String> kChainRpcs = {
  'eth': 'https://eth.llamarpc.com',
  'arb': 'https://arb1.arbitrum.io/rpc',
  'base': 'https://mainnet.base.org',
  'bsc': 'https://bsc-dataseed.binance.org',
  'poly': 'https://polygon-rpc.com',
  'op': 'https://mainnet.optimism.io',
  'avax': 'https://api.avax.network/ext/bc/C/rpc',
  'cro': 'https://evm.cronos.org',
  'monad': 'https://rpc.monad.xyz',
  'xpl': 'https://rpc.plasma.to',
  'pls': 'https://rpc.pulsechain.com',
  'uni': 'https://mainnet.unichain.org',
  'rh': 'https://rpc.mainnet.chain.robinhood.com',
  'bob': 'https://rpc.nodeflare.app/bob/public',
  'gleec': 'https://evm-rpc.gleec.com',
  'linea': 'https://rpc.linea.build',
  'zksync': 'https://mainnet.era.zksync.io',
  'hyperevm': 'https://rpc.hyperliquid.xyz/evm',
  'ink': 'https://rpc-gel.inkonchain.com',
  'rsk': 'https://public-node.rsk.co',
  'gnosis': 'https://rpc.gnosischain.com',
  'flare': 'https://flare-api.flare.network/ext/C-rpc',
  'kaia': 'https://public-en.node.kaia.io',
  'scroll': 'https://rpc.scroll.io',
  'abstract': 'https://rpc.abstract.xyz',
  'plume': 'https://rpc.plume.org',
  'soneium': 'https://rpc.soneium.org',
  'doma': 'https://rpc.doma.xyz',
  'beam': 'https://build.onbeam.com/rpc',
  'moonriver': 'https://rpc.api.moonriver.moonbeam.network',
  'peaq': 'https://peaq.api.onfinality.io/public',
  'tempo': 'https://rpc.tempo.xyz',
  'sei': 'https://evm-rpc.sei-apis.com',
};

const Map<String, String> kChainNames = {
  'eth': 'Ethereum',
  'arb': 'Arbitrum',
  'base': 'Base',
  'bsc': 'BNB Chain',
  'poly': 'Polygon',
  'op': 'OP Mainnet',
  'avax': 'Avalanche',
  'cro': 'Cronos',
  'monad': 'Monad',
  'xpl': 'Plasma',
  'pls': 'PulseChain',
  'uni': 'Unichain',
  'rh': 'Robinhood Chain',
  'bob': 'BOB',
  'gleec': 'Gleec Chain',
  'linea': 'Linea',
  'zksync': 'ZKsync Era',
  'hyperevm': 'HyperEVM',
  'ink': 'Ink',
  'rsk': 'Rootstock',
  'gnosis': 'Gnosis',
  'flare': 'Flare',
  'kaia': 'Kaia',
  'scroll': 'Scroll',
  'abstract': 'Abstract',
  'plume': 'Plume',
  'soneium': 'Soneium',
  'doma': 'Doma',
  'beam': 'Beam',
  'moonriver': 'Moonriver',
  'peaq': 'peaq',
  'tempo': 'Tempo',
  'sei': 'Sei',
};

const Map<String, int> kChainColors = {
  'eth': 0x627EEA,
  'arb': 0x28A0F0,
  'base': 0x0052FF,
  'bsc': 0xF0B90B,
  'poly': 0x8247E5,
  'op': 0xFF0420,
  'avax': 0xE84142,
  'cro': 0x002D74,
  'monad': 0x836EF9,
  'xpl': 0x4FA9E0,
  'pls': 0x9C27B0,
  'uni': 0xFF007A,
  'rh': 0x6B7280,
  'bob': 0xFF6D00,
  'gleec': 0x00A3C4,
  'linea': 0x61DFFF,
  'zksync': 0x8C8DFC,
  'hyperevm': 0x97FCE4,
  'ink': 0x7132F5,
  'rsk': 0xE9B64E,
  'gnosis': 0x1D6C4E,
  'flare': 0xE6413E,
  'kaia': 0xFF1D01,
  'scroll': 0xEBC28E,
  'abstract': 0x202020,
  'plume': 0xFF3D00,
  'soneium': 0x937DFF,
  'doma': 0x4F46E5,
  'beam': 0x0BDBB5,
  'moonriver': 0xF5B700,
  'peaq': 0x7A2BF5,
  'tempo': 0x111111,
  'sei': 0x9E1F19,
};

const Set<String> kWalletTierKeys = {
  'op',
  'avax',
  'cro',
  'monad',
  'xpl',
  'pls',
  'uni',
  'rh',
  'bob',
  'gleec',
  'linea',
  'zksync',
  'hyperevm',
  'ink',
  'rsk',
  'gnosis',
  'flare',
  'kaia',
  'scroll',
  'abstract',
  'plume',
  'soneium',
  'doma',
  'beam',
  'moonriver',
  'peaq',
  'tempo',
  'sei',
};
