// CryptoNoteWalletConfig.h
#ifndef CRYPTONOTEWALLETCONFIG_H
#define CRYPTONOTEWALLETCONFIG_H

// Wallet configuration constants
#define WALLET_VERSION_MAJOR 1
#define WALLET_VERSION_MINOR 0
#define WALLET_VERSION_PATCH 0
#define WALLET_CURRENCY_DISPLAY_NAME "XFG"
#define WALLET_CURRENCY_TICKER "XFG"

#endif // CRYPTONOTEWALLETCONFIG_H
